### ISSUE TITLE
[Suggestion] missing several papers in 4D AIGC

### ISSUE THREAD

**Issue by WUMINGCHAzero** [mdyao/Awesome-3D-AIGC#11]
1. Text-to-4d dynamic scene generation (https://arxiv.org/abs/2301.11280)  ICML 2023
2. Consistent4D: Consistent 360° Dynamic Object Generation from Monocular Video (https://arxiv.org/abs/2311.02848) ICLR 2024
3. Align Your Gaussians: Text-to-4D with Dynamic 3D Gaussians and Composed Diffusion Models (https://arxiv.org/abs/2312.13763)
4. Animate124: Animating One Image to 4D Dynamic Scene (https://arxiv.org/abs/2311.14603)
5. A Unified Approach for Text- and Image-guided 4D Scene Generation (https://arxiv.org/abs/2311.16854)

**Comment by mdyao** [comment]
Your suggestion is greatly appreciated. We will incorporate them ASAP.
