### ISSUE TITLE
Request for paper update

### ISSUE THREAD

**Issue by huanngzh** [mdyao/Awesome-3D-AIGC#17]
1. EpiDiff: Enhancing Multi-View Synthesis via Localized Epipolar-Constrained Diffusion [CVPR 2024] - https://huanngzh.github.io/EpiDiff/
2. Ouroboros3D: Image-to-3D Generation via 3D-aware Recursive Diffusion - https://costwen.github.io/Ouroboros3D/

**Comment by mdyao** [comment]
Please submit a pull request directly, and I will merge it into the main repository. THX.
